# Generated by Django 3.2.6 on 2021-09-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20210915_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(blank=True, default='', unique=True),
        ),
    ]
